language: node_js
node_js:
  - "0.10"

services:
  - mongodb

install:
  - npm install
  - ./node_modules/bower/bin/bower install

before_script:
  - sh ./test_build.sh
  - npm install -g grunt-cli
  - npm install -g phantomjs
  - mysql -e 'create database gridpaste;'
  - mongo gridpaste --eval 'db.addUser("travis", "test");'
  - node ./environment/replay.js


script: grunt test
