version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: gridpaste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./run/pg:/var/lib/postgresql/data
